// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateEntry(ctx context.Context, arg CreateEntryParams) error
	CreateTransfer(ctx context.Context, arg CreateTransferParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetEntryByAccount(ctx context.Context, arg GetEntryByAccountParams) ([]Entry, error)
	GetLastAccount(ctx context.Context) (Account, error)
	GetLastEntry(ctx context.Context) (Entry, error)
	GetLastTransfer(ctx context.Context) (Transfer, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetTransferByFromAccount(ctx context.Context, arg GetTransferByFromAccountParams) ([]Transfer, error)
	GetTransferByFromAccountAndToAccount(ctx context.Context, arg GetTransferByFromAccountAndToAccountParams) ([]Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) error
	UpdateTransfer(ctx context.Context, arg UpdateTransferParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
